### ISSUE TITLE
Add Syncing and Mapping of Classification/CloseCode

### ISSUE THREAD

**Issue by ChristSent** [Sebmolendijk/snow_v2#14]
Sentinel offers classification, classificationComment, and classificatoinReason out of the box.

**Classification:** BenignPositive, FalsePositive, TruePositive, and Undetermined
**classificatoinReason:** InaccurateData, IncorrectAlertLogic, SuspiciousActivity, SuspiciousButExpected
**classificationComment:** Custom comments written by a user.

Surprisingly the Sentinel UI only allows for 5 unique combinations of Classification/classificationReason.

1. TruePositive - SuspiciousActivity
2. BenignPositive - SuspiciousButExpected
3. FalsePositive - IncorrectAlertLogic
4. FalsePositive - InaccurateData
5. Undetermined

ServiceNow offers close_code and close_notes

I propose that we handle this the same as: State and Severity
That we make a custom mapping from Sentinel's 5 unique combos of classification/classificationReason to whatever customer's have for close_code in ServiceNow. 

In my particular case I've got about 8 different close_codes I want to handle in ServiceNow. So the first 4 would map to 1-4 above. The last 4 would map to 5. Undetermined.

Thoughts?

**Comment by Sebmolendijk** [comment]
Added in code
