### ISSUE TITLE
No support for alternate management endpoints.

### ISSUE THREAD

**Issue by ChristSent** [Sebmolendijk/snow_v2#7]
Azure has a few endpoints. In particular, I need management.govcloudapi.net.
I noticed management.azure.com is hardcoded in AppUtils.js 
It is in a few other places as well.
Maybe this setting can be extracted to the workspace configuration?

**Comment by Sebmolendijk** [comment]
Added a variable using a system property (apiUrl) to replace the hardcoded url in AppUtils.

**Comment by ChristSent** [comment]
Tested works for me. Closing issue. Thanks!
