### ISSUE TITLE
Cannot update Sentinel incident on change due to unretrievable environment id

### ISSUE THREAD

**Issue by ChristSent** [Sebmolendijk/snow_v2#8]
When I change the status of my SNOW incident from Contain to Eradicate I get the following error:

2021-04-20  15:17:34 | Information | ERROR updating incident (business rule)SIR0010056 Business rule - update_changes_to_sentinelenvironment as33dev Azure Sentinel incidentnot found!
-- | -- | --

These are 2 separate errors. Both  from update_changes_to_sentinel.
**Line 70:** appUtils.log('ERROR updating incident (business rule)' + current.number + '\n' + message);
**Line 18:** throw {'type': 'UnknownEnvironmentId', 'message': 'Business rule - update_changes_to_sentinelenvironment \n' + **environmentId** + 'not found!'};

The environmentId variable is not being retrieved properly due to AppUtils Line 108 - 113:
getEnvironmentId: function(incident) {
        var environmentId = incident.description.split('\n');
        environmentId = environmentId.pop().split(':')[1].trim();
    
        return environmentId;
    },

The problem is that my incident description has changed. I didn't even change it intentionally. At some point I think I just clicked in the box and that cause some of the html to get reformatted. So now it's actually pulling the begging of the description or something.

I don't think this is a reliable way to retrieve the environment ID. I'd recommend storing the environment id in the Incident Metadata table at incident creation time. Then when an incident is updated the environment id can be retrieved from the Incident Metadata table using the incident id.

I believe storing the environment id in the incident metadata table is just a matter of editing SentinelIncidents script:
Line 338:
// Update metadata counters
                        var incidentMetadata = appUtils.setIncidentMetadata(myObj.sys_id, incidentAlerts.length, incidentEntities.length);
                    }

**Comment by ChristSent** [comment]
I see you made a bunch of changes to SentinelIncidents and AppUtils. They worked for me. 
I just had to make one more change to getEnvironmentID in apputils. I submitted a PR for that. Feel free to change to your liking.

**Comment by Sebmolendijk** [comment]
I added to your PR support for environment ID missing from the metadata table but having the environment ID in the description, like in my environment or a couple of others.
It's now first looking in the table and try to fallback to description if the table doesn't have the information

**Comment by ChristSent** [comment]
Awesome, I updated all the scripts on my instance to match this repo and its working! Closing issue.
